### ISSUE TITLE
Is it an evaluation bug?

### ISSUE THREAD

**Issue by jasonwu0731** [budzianowski/multiwoz#1]
hello,

In this two lines,
https://github.com/budzianowski/multiwoz/blob/master/model/evaluator.py#L212 
https://github.com/budzianowski/multiwoz/blob/master/model/evaluator.py#L362

The "venue_offered[domain]" is a string, so the [0] will give you just a token "[", I think the "venue_offered[domain][0] in goal_venues" does not do the logic you try to do. 

Please check if this makes any mistake in your evaluation. Thanks.

**Comment by budzianowski** [comment]
Hi Jason,

thanks for spotting this out! I will run evaluation to see if the numbers are different and report results later on.
