### ISSUE TITLE
Mirror of the dataset

### ISSUE THREAD

**Issue by stephenroller** [budzianowski/multiwoz#13]
Hi Paweł,

Do you know if there's are mirrors of the dataset anywhere? The cambridge website has reported that it's under maintenance for a couple weeks now.

Cheers,
Stephen

https://github.com/budzianowski/multiwoz/blob/9fd409ffff25fea5ef892db6054380c35691c9c4/create_delex_data.py#L267

**Comment by budzianowski** [comment]
Hi Stephen! Thanks for spotting this - it seems like the repository website is alive again. I'm sorry for the trouble - the whole point of storing data there was to keep it in reliable place (sic!).
