### ISSUE TITLE
dialog_acts.json does not exist in Multizwoz 2.1 

### ISSUE THREAD

**Issue by jin8** [budzianowski/multiwoz#16]
Is it okay to use dialog_acts.json that was used in version 2.0?
Or is it that the version 2.1 does not require dialog_act.json?

**Comment by jin8** [comment]
I was able to find the dialog_act.json for Multizwoz 2.1 at this url https://www.repository.cam.ac.uk/handle/1810/294507

**Comment by rgtjf** [comment]
@jin8 I have the same questions when I tried to handle `multizwoz 2.1`.  I found that `dialog_act.json` is the same as `system_acts.json`. 

If possible, could you paste your scripts via gist? Thanks a lot
