### ISSUE TITLE
About requestable slots for success rate

### ISSUE THREAD

**Issue by gusalsdmlwlq** [budzianowski/multiwoz#18]
Hi, I have a question about requestable slots for success rate.
https://github.com/budzianowski/multiwoz/blob/d5f0a569fb68e610b3e396dddeadab9072b6c96d/evaluate.py#L210
In evaluate.py, requestables just includes 5 slots('phone', 'address', 'postcode', 'reference', 'id').
But, there are more requestable slots in user's goal.
ex) train-price, taxi-car type, attraction-entrance fee...
Why does it evaluate just 5 slots?

**Comment by budzianowski** [comment]
Although there are more requestable slots, to have a successful conversation only these 5 slots were required.
