### ISSUE TITLE
DB: Booking availability is not provided in database

### ISSUE THREAD

**Issue by ehosseiniasl** [budzianowski/multiwoz#21]
In db pointer vector, there is information of whether booking is available or not.
Is there a way that using predicted belief states, we compute booking availability for the retrieved entities?

Example:
for the attached example with following gold belief on restaurant, the retried entity has booking=available in db pointer vector, but there is no booking information in the restaurant db

`belief : {'pricerange': 'cheap', 'area': 'centre', 'name': 'dojo noodle bar'}`

`retrieved restaurant: ('19225',
  '40210 Millers Yard City Centre',
  'centre',
  'asian oriental',
  'dojo noodle bar serves a variety of japanese chinese vietnamese korean and malaysian dishes to eat in or take away sister restaurant to touzai',
  'dojo noodle bar',
  '01223363471',
  'cb21rq',
  'cheap',
  'NULL',
  'restaurant')`

![Screen Shot 2020-04-29 at 2 00 02 PM](https://user-images.githubusercontent.com/6238049/80646917-75e9d000-8a22-11ea-856f-bdfacb89e402.png)

@budzianowski 
cc: @bmccann

**Comment by budzianowski** [comment]
If you look at the goal of the dialogue, the restaurant domain has information that the booking will fail at 6:30 and it will work for 5:30. This how you can check what booking is possible.
<img width="384" alt="Screen Shot 2020-05-05 at 22 56 33" src="https://user-images.githubusercontent.com/17451096/81115260-b619e880-8f23-11ea-858c-871cabf10e68.png">


PS: Please download the lataset version of the dataset

**Comment by bmccann** [comment]
Follow up question on this dictionary entries.

So if the model somehow generated a request for a booking at 16:30, does that booking fail? What about if a request is made at 19:30?

**Comment by budzianowski** [comment]
The booking was failing for all times except 17:30.

**Comment by bmccann** [comment]
Got it, thanks!
