### ISSUE TITLE
New results on dialogue state tracking , policy optimization

### ISSUE THREAD

**Issue by ehosseiniasl** [budzianowski/multiwoz#22]
We have released our new results on arxiv 

**A Simple Language Model for Task-Oriented Dialogue**
**TL;DR:** SimpleTOD is a simple approach to task-oriented dialogue that uses a single causal language model trained on all sub-tasks recast as a single sequence prediction problem.
https://arxiv.org/abs/2005.00796

Belief Tracking:
```
version      joint acc
2.1          55.72

```
Policy Optimization:
```
version     Inform    Success       Bleu
2.0          84.4       70.1        15.01
2.1          85         70.5        15.23
```

@budzianowski do you update the leaderboard? Or should we open a PR?
cc @bmccann

**Comment by TonyNemo** [comment]
@ehosseiniasl Hi there, excellent work, I really enjoy it.
However, I notice in your paper that the results of BLEU of the generated response are unseasonably high. Given the one-to-many nature of dialog, a BLEU of 50 is like almost identical to the ground truth response, even SOTA in NMT is just around 30.
Can you opensource your code so we can reproduce the results or briefly clarify my concerns?
Thx.

**Comment by ehosseiniasl** [comment]
Thanks for noticing this. 
We already fixed the bleu scores and let the MultiWOZ author know to update the leaderboard.
