### ISSUE TITLE
Hyperparameter of trade on MultiWOZ 2.1

### ISSUE THREAD

**Issue by function2-llx** [budzianowski/multiwoz#25]
Hello,

I'm conducting some experiments with trade on MultiWOZ 2.1. I simply replaced the dataset used by [trade](https://github.com/jasonwu0731/trade-dst), which experiments on MultiWOZ 2.0,  with the hyperparameters unchange., However, this only reached an accuracy of 35% approximately. This result is much lower than the result this paper reported, which I guess it may be an issue of hyperparameters of the trade model.

However, I'm not able to find any reference related to this, I even have no idea if the hyperparameters of trade, or other models, change between these two datasets. I wonder if it is possible for me to get the specific values of these hyperparamters of models on MultiWOZ 2.1, so I could reproduce the result? Thanks in advance.

**Comment by budzianowski** [comment]
Hi, sorry for the delay. Please contact the authors of the TRADE model as I'm not related with their publication.
