### ISSUE TITLE
data

### ISSUE THREAD

**Issue by lytum** [budzianowski/multiwoz#26]
Hi,

May I ask, whether the three MultiWOZ dataset in your folder data/ are same as downloaded from https://www.repository.cam.ac.uk/handle/1810/294507
Thanks for your feedback.

I want to the storage structure of this dataset, so just ran 'create_delex_data.py' and also read all of the source code in this script. But i still confused about "db" and "bs". could you help me explain something about these two variables? Thanks in advance!

**Comment by budzianowski** [comment]
Hi,

1) Yes, the data is the same
2) db is a vectorial representation how many entities satisfy the constraint of the search at the current point of the dialogue
bs is a vectorial representation of what slots are mentioned.
