### ISSUE TITLE
Which version of pytorch are you using?

### ISSUE THREAD

**Issue by Jiahuan-Pei** [budzianowski/multiwoz#3]
Hi Budzianowski,
Have you run the code on GPUs? I cannot make it. So may I know which version of Pytorch are you using?

**Comment by terryqj0107** [comment]
I have the same question. Which python version and pytorch version are used here?

**Comment by pawel-polyai** [comment]
The code was written in PyTorch 0.4.1 I will be soon moving it to Pytorch 1.0

**Comment by budzianowski** [comment]
The code was written in pytorch 0.4.1 so you will have to define devices with some tensors explicitly. I will be soon moving to pytorch 1.0!
