### ISSUE TITLE
The annotation tool

### ISSUE THREAD

**Issue by anbo724** [budzianowski/multiwoz#30]
I want to annotate similar data for different language,  thus I want to build a web-based annotation tool, can you share the code of annotation tool or any suggestion?
Thanks.

**Comment by budzianowski** [comment]
The annotation tool was coupled with the university stack and as such cannot be published. Let me know if you have questions about the details of the set-up.

**Comment by lexmen318** [comment]
@anbo724 I would like to recommend you an annotation tool developed by us: https://github.com/lexmen318/metaCAT.
enjoy it and give as many comments as possible:)
