### ISSUE TITLE
a error in the data.json

### ISSUE THREAD

**Issue by lytum** [budzianowski/multiwoz#31]
Hi,
I found  "span_info" of text: "The city centre north b and b has parking and wifi. It is in the north area. Would you like to book this hotel?" an error, i think the index of the value ' north' should. be the second 'north', the first 'north' is a part of name 'city centre north b and b'. could you modify that?
details in he following

"text": "The city centre **north** b and b has parking and wifi. It is in the **north** area. Would you like to book this hotel?",
                "metadata": {
                    "taxi": {
                        "book": {
                            "booked": []
                        },
                        "semi": {
                            "leaveAt": "",
                            "destination": "",
                            "departure": "",
                            "arriveBy": ""
                        }
                    },
                    "police": {
                        "book": {
                            "booked": []
                        },
                        "semi": {}
                    },
                    "restaurant": {
                        "book": {
                            "booked": [
                                {
                                    "name": "nandos city centre",
                                    "reference": "LYIENP77"
                                }
                            ],
                            "people": "4",
                            "day": "wednesday",
                            "time": "15:00"
                        },
                        "semi": {
                            "food": "not mentioned",
                            "pricerange": "not mentioned",
                            "name": "nandos city centre",
                            "area": "not mentioned"
                        }
                    },
                    "hospital": {
                        "book": {
                            "booked": []
                        },
                        "semi": {
                            "department": ""
                        }
                    },
                    "hotel": {
                        "book": {
                            "booked": [],
                            "people": "",
                            "day": "",
                            "stay": ""
                        },
                        "semi": {
                            "name": "not mentioned",
                            "area": "not mentioned",
                            "parking": "yes",
                            "pricerange": "not mentioned",
                            "stars": "0",
                            "internet": "yes",
                            "type": "guesthouse"
                        }
                    },
                    "attraction": {
                        "book": {
                            "booked": []
                        },
                        "semi": {
                            "type": "",
                            "name": "",
                            "area": ""
                        }
                    },
                    "train": {
                        "book": {
                            "booked": [],
                            "people": ""
                        },
                        "semi": {
                            "leaveAt": "",
                            "destination": "",
                            "day": "",
                            "arriveBy": "",
                            "departure": ""
                        }
                    }
                },
                "dialog_act": {
                    "Booking-Inform": [
                        [
                            "none",
                            "none"
                        ]
                    ],
                    "Hotel-Inform": [
                        [
                            "Name",
                            "city centre north b and b"
                        ],
                        [
                            "Area",
                            "north"
                        ],
                        [
                            "Internet",
                            "none"
                        ],
                        [
                            "Parking",
                            "none"
                        ]
                    ]
                },
                "span_info": [
                    [
                        "Hotel-Inform",
                        "Name",
                        "city centre north b and b",
                        1,
                        6
                    ],
                    [
                        "Hotel-Inform",
                        "Area",
                        "north",
                        **3,
                        3**
                    ]
                ]
            },

**Comment by budzianowski** [comment]
Thanks for the catch!
I've let the MultiWOZ 2.2 authors know and they will try to correct these span annotations and include them in the next release.

**Comment by budzianowski** [comment]
This is now fixed in 2.2
