### ISSUE TITLE
Hospital database is not complete

### ISSUE THREAD

**Issue by LarsLiden** [budzianowski/multiwoz#34]
The training data contains goals asking for hospital name, postcode and address, but the hospital database only contains departments and phone numbers.  Any idea where the complete hospital database could be found?  It must exist for the training data to have been created.  For example:  "Addenbrookes Hospital on Hills Rd".

**Comment by budzianowski** [comment]
Hi,
thanks for pointing this out! The address is:
Telephone: 01223245151
Address: Hills Rd, Cambridge
Postcode: CB20QQ

I updated the db file.
