### ISSUE TITLE
[ERROR] in MultiWOZ 2.1

### ISSUE THREAD

**Issue by ShaneTian** [budzianowski/multiwoz#42]
Some conversations have no `dialog_act` annotation in MultiWOZ 2.1:
- `PMUL4707.json`
- `PMUL2245.json`
- `PMUL4776.json`
- `PMUL3872.json`
- `PMUL4859.json`

**Comment by budzianowski** [comment]
@mihail911

**Comment by XiaoxueZang** [comment]
MultiWOZ 2.2 manually added dialogue actions for them. Please feel free to let me know if you have any questions.

**Comment by budzianowski** [comment]
@ShaneTian  - I recommend using version 2.2.
