### ISSUE TITLE
2.2 action annotations missing?

### ISSUE THREAD

**Issue by david-wb** [budzianowski/multiwoz#45]
The 2.2 dataset doesn't appear to have any system action annotations at all. The json format for it is convenient, but it isn't useful to me without the action annotations. Will they be added soon?

**Comment by jianguoz** [comment]
> The 2.2 dataset doesn't appear to have any system action annotations at all. The json format for it is convenient, but it isn't useful to me without the action annotations. Will they be added soon?

Hi, the action annotations are already updated by authors of 2.2, and now are waiting to be merged to this repository. If necessary, You can also directly contact Xiaoxue (xiaoxuez@google.com) to get the new dataset before it is updated here.

**Comment by david-wb** [comment]
@jianguoz Thanks, I obtained a download link from Xiaoxue.
