### ISSUE TITLE
New SoTA for Policy optimization and end-to-end generation

### ISSUE THREAD

**Issue by nflubis** [budzianowski/multiwoz#52]
Hello,

We have just published our work which reach new SoTA for policy optimization and end-to-end generation tasks.
https://www.aclweb.org/anthology/2020.coling-main.41.pdf

Policy optimization
Match/Success/BLEU
MW 2.0: 97.50/94.80/0.12
MW 2.1: 96.39/83.57/0.14

End-to-End generation
Match/Success/BLEU
MW 2.0: 91.80/81.80/0.12

Would it be possible to include this work on the page? Thank you!

**Comment by budzianowski** [comment]
Hi Nulu, can you make a PR with updated readme?
