### ISSUE TITLE
Some Questions on Benchmarks

### ISSUE THREAD

**Issue by ToSev7en** [budzianowski/multiwoz#6]
Natural Language Generation

<img width="440" alt="image" src="https://user-images.githubusercontent.com/9492778/62223959-6a606e80-b3e8-11e9-897a-607c8fff2c6f.png">

Here the Baseline (Budzianowski et al. 2018 https://pdfs.semanticscholar.org/47d0/1eb59cd37d16201fcae964bd1d2b49cfb55e.pdf) model got the BLEU score 0.632。

However, when I read the experiment records in the paper , there is no where to find such BLEU score. 

<img width="793" alt="image" src="https://user-images.githubusercontent.com/9492778/62224074-a7c4fc00-b3e8-11e9-9979-659869bae798.png">

**Comment by budzianowski** [comment]
Hi, the first table refers to the different experiment - Dialogue-Act-to-Text Generation. To re-create these results please go to https://github.com/andy194673/nlg-sclstm-multiwoz
