### ISSUE TITLE
MultiWOZ2.2 

### ISSUE THREAD

**Issue by lytum** [budzianowski/multiwoz#66]
I just run the "convert_to_multiwoz_format.py" in MultiWOZ2.2, there is the following error:

  File "convert_to_multiwoz_format.py", line 85, in main
    clean_dialogue = clean_data[dialogue_id]
KeyError: 'SNG01862.json'

it seems there is no 'SNG01862.json' in the dialogue_acts.json file. how to fit it? @XiaoxueZang 

Thanks in advance.

**Comment by XiaoxueZang** [comment]
"SNG01862.json" is removed from MultiWOZ 2.2 in our recent update as it's a meaningless dialogue. Could you try just skipping it in the code? I'll update the script to fix this.

**Comment by XiaoxueZang** [comment]
Yes, that is the only one removed. I've updated the script and readme.

**Comment by lytum** [comment]
Thanks a lot!!
