### ISSUE TITLE
Inform and Success metrics

### ISSUE THREAD

**Issue by Aishwarya-NR** [budzianowski/multiwoz#7]
Hi, 
I don't seem to understand the inform metric very well. What do you exactly mean by providing the right entity and why is the inform rate not 100% even with the oracle belief state. Does this mean that dialogue state prediction systems must do better than oracle in-order to improve inform rate?

**Comment by budzianowski** [comment]
By providing the right entity I mean the situation when the system informed about the right entity at the right time. Even with oracle belief state the system could inform about some venue too fast while the user has changed her preferences later on. In this case, if the system did not inform about the new entity, the dialogue will be unsuccessful. That is why is not 100% even with perfect information.
