### ISSUE TITLE
Evaluation tools for belief tracking?

### ISSUE THREAD

**Issue by SparkJiao** [budzianowski/multiwoz#8]
Hi, I wanna know is there an official evaluation tool for dialog belief tracking? The code of **TRADE** is built-in and confusing...

**Comment by pawel-polyai** [comment]
Hi, there is no official code. However, the final metric is fairly straightforward to implement. If all the predicted slots in the turn match the ground truthvalues, the output is considered correct. Then you average over all turns.

**Comment by budzianowski** [comment]
Hi, there is no official code. However, the final metric is fairly straightforward to implement. If all the predicted slots in the turn match the ground truthvalues, the output is considered correct. Then you average over all turns.
