### ISSUE TITLE
NLTK doesn't support python 2.* anymore, code needs update.

### ISSUE THREAD

**Issue by jimimvp** [budzianowski/multiwoz#81]
NLTK breaks when trying to run `create_delex_data.py`, there are syntax errors resulting. The solution would be to either specify the **exact** versions of the packages used in `requirements.txt ` or update the code to python 3.

**Comment by Yevgnen** [comment]
Same issue.

**Comment by Yevgnen** [comment]
`nltk==3.4.5` seems work.
