### ISSUE TITLE
Python 2 Depreciation

### ISSUE THREAD

**Issue by amiralikaboli** [budzianowski/multiwoz#93]
Hi!

Your preprocessing script in `create_delex_data.py` is a good start for working with Multiwoz. But, it was implemented in Python 2 that is depreciated. I refactored this part and dependent codes for being compatible in Python 3 once for my research project that I think can help others. I want to ask may I push them and make a pull request?

Thanks!

**Comment by jianguoz** [comment]
Hi @amiralikaboli, thanks for your message, you are much welcome to push them with pull requests!

**Comment by amiralikaboli** [comment]
Unfortunately, I think I don't have permission to push a new branch. @jianguoz

**Comment by amiralikaboli** [comment]
Could you give me this permission temporary? Or do you have any other suggestion? @budzianowski

**Comment by amiralikaboli** [comment]
I have made a pull request https://github.com/budzianowski/multiwoz/pull/96
@jianguoz

**Comment by jianguoz** [comment]
@amiralikaboli Thanks very much for your contribution! I have merged the pull request.
